(cl:in-package ueyecam-srv)
(cl:export '(EDGEENHANCEMENTSET-VAL
          EDGEENHANCEMENTSET
          EDGEENHANCEMENTGET-VAL
          EDGEENHANCEMENTGET
          EDGEENHANCEMENTGETSTRING-VAL
          EDGEENHANCEMENTGETSTRING
))