/* Auto-generated by genmsg_cpp for file /home/topo/ros/topokite/ueyecam/srv/setROIFull.srv */
#ifndef UEYECAM_SERVICE_SETROIFULL_H
#define UEYECAM_SERVICE_SETROIFULL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace ueyecam
{
template <class ContainerAllocator>
struct setROIFullRequest_ {
  typedef setROIFullRequest_<ContainerAllocator> Type;

  setROIFullRequest_()
  : fullON(false)
  {
  }

  setROIFullRequest_(const ContainerAllocator& _alloc)
  : fullON(false)
  {
  }

  typedef uint8_t _fullON_type;
  uint8_t fullON;


private:
  static const char* __s_getDataType_() { return "ueyecam/setROIFullRequest"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "16d2ed52ec05b432671f3d0db1025dd1"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "16d2ed52ec05b432671f3d0db1025dd1"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "bool fullON\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, fullON);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, fullON);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(fullON);
    return size;
  }

  typedef boost::shared_ptr< ::ueyecam::setROIFullRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ueyecam::setROIFullRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct setROIFullRequest
typedef  ::ueyecam::setROIFullRequest_<std::allocator<void> > setROIFullRequest;

typedef boost::shared_ptr< ::ueyecam::setROIFullRequest> setROIFullRequestPtr;
typedef boost::shared_ptr< ::ueyecam::setROIFullRequest const> setROIFullRequestConstPtr;


template <class ContainerAllocator>
struct setROIFullResponse_ {
  typedef setROIFullResponse_<ContainerAllocator> Type;

  setROIFullResponse_()
  {
  }

  setROIFullResponse_(const ContainerAllocator& _alloc)
  {
  }


private:
  static const char* __s_getDataType_() { return "ueyecam/setROIFullResponse"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d41d8cd98f00b204e9800998ecf8427e"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getServerMD5Sum_() { return "16d2ed52ec05b432671f3d0db1025dd1"; }
public:
  ROS_DEPRECATED static const std::string __s_getServerMD5Sum() { return __s_getServerMD5Sum_(); }

  ROS_DEPRECATED const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    return size;
  }

  typedef boost::shared_ptr< ::ueyecam::setROIFullResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ueyecam::setROIFullResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct setROIFullResponse
typedef  ::ueyecam::setROIFullResponse_<std::allocator<void> > setROIFullResponse;

typedef boost::shared_ptr< ::ueyecam::setROIFullResponse> setROIFullResponsePtr;
typedef boost::shared_ptr< ::ueyecam::setROIFullResponse const> setROIFullResponseConstPtr;

struct setROIFull
{

typedef setROIFullRequest Request;
typedef setROIFullResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct setROIFull
} // namespace ueyecam

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ueyecam::setROIFullRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ueyecam::setROIFullRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ueyecam::setROIFullRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "16d2ed52ec05b432671f3d0db1025dd1";
  }

  static const char* value(const  ::ueyecam::setROIFullRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x16d2ed52ec05b432ULL;
  static const uint64_t static_value2 = 0x671f3d0db1025dd1ULL;
};

template<class ContainerAllocator>
struct DataType< ::ueyecam::setROIFullRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ueyecam/setROIFullRequest";
  }

  static const char* value(const  ::ueyecam::setROIFullRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ueyecam::setROIFullRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool fullON\n\
\n\
";
  }

  static const char* value(const  ::ueyecam::setROIFullRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ueyecam::setROIFullRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ueyecam::setROIFullResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ueyecam::setROIFullResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ueyecam::setROIFullResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::ueyecam::setROIFullResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ueyecam::setROIFullResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ueyecam/setROIFullResponse";
  }

  static const char* value(const  ::ueyecam::setROIFullResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ueyecam::setROIFullResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
";
  }

  static const char* value(const  ::ueyecam::setROIFullResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::ueyecam::setROIFullResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ueyecam::setROIFullRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.fullON);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setROIFullRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ueyecam::setROIFullResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct setROIFullResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<ueyecam::setROIFull> {
  static const char* value() 
  {
    return "16d2ed52ec05b432671f3d0db1025dd1";
  }

  static const char* value(const ueyecam::setROIFull&) { return value(); } 
};

template<>
struct DataType<ueyecam::setROIFull> {
  static const char* value() 
  {
    return "ueyecam/setROIFull";
  }

  static const char* value(const ueyecam::setROIFull&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<ueyecam::setROIFullRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "16d2ed52ec05b432671f3d0db1025dd1";
  }

  static const char* value(const ueyecam::setROIFullRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<ueyecam::setROIFullRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ueyecam/setROIFull";
  }

  static const char* value(const ueyecam::setROIFullRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<ueyecam::setROIFullResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "16d2ed52ec05b432671f3d0db1025dd1";
  }

  static const char* value(const ueyecam::setROIFullResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<ueyecam::setROIFullResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ueyecam/setROIFull";
  }

  static const char* value(const ueyecam::setROIFullResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // UEYECAM_SERVICE_SETROIFULL_H

